[[redirects]]
from="/MoviesAppReact"
to="https://shubhamverma1811.github.io/MoviesAppReact"

[[redirects]]
from="/Unsplash-React"
to="https://shubhamverma1811.github.io/Unsplash-React"

[[redirects]]
from="/Insure"
to="https://shubhamverma1811.github.io/Insure"

[[redirects]]
from="/7D7W"
to="https://shubhamverma1811.github.io/7D7W"