[[redirects]]
from="/MoviesAppReact"
to="https://shubhamverma1811.github.io/MoviesAppReact"

[[redirects]]
from="/Unsplash-React"
to="https://shubhamverma1811.github.io/Unsplash-React"

[[redirects]]
from="/Insure"
to="https://shubhamverma1811.github.io/Insure"

[[redirects]]
from="/7D7W"
to="https://shubhamverma1811.github.io/7D7W"

[[redirects]]
from="/QuizAppReact"
to="https://shubhamverma1811.github.io/QuizAppReact"

[[redirects]]
from="/Weathery"
to="https://shubhamverma1811.github.io/Weathery"

[[redirects]]
from="/Manage"
to="https://shubhamverma1811.github.io/Manage"

[[redirects]]
from="/PTracking"
to="https://shubhamverma1811.github.io/PTracking"

[[redirects]]
from="/Shortly"
to="https://shubhamverma1811.github.io/Manage"Shortly

[[redirects]]
from="/Huddle"
to="https://shubhamverma1811.github.io/Huddle"

[[redirects]]
from="/Fylo"
to="https://shubhamverma1811.github.io/Fylo"

[[redirects]]
from="/Manage"
to="https://shubhamverma1811.github.io/Manage"

[[redirects]]
from="/rgbgame"
to="https://shubhamverma1811.github.io/rgbgame"

[[redirects]]
from="/patatapClone"
to="https://shubhamverma1811.github.io/patatapClone"

[[redirects]]
from="/LCO"
to="https://shubhamverma1811.github.io/LCO"

[[redirects]]
from="/BaseApparel"
to="https://shubhamverma1811.github.io/BaseApparel"

[[redirects]]
from="/Manage"
to="https://shubhamverma1811.github.io/Manage"

[[redirects]]
from="/EasyBank"
to="https://shubhamverma1811.github.io/EasyBank"